/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/* Software version 1.0.0.23072021  */ 
package com.FinalUI;

import java.sql.*;
import java.io.*;
import java.util.Arrays;
import java.util.Locale;
import javax.swing.JComboBox;

/**
 *
 * @author AliS2019
 */
public class DesignUI extends javax.swing.JFrame{

    /**
     * Creates new form DesignUI
     */
    public DesignUI() {
        initComponents();
    }
   /*     
private Country[] createCountryList() {
    String[] countryCodes = Locale.getISOCountries();
    Country[] listCountry = new Country[countryCodes.length];
 
    for (int i = 0; i < countryCodes.length; i++) {
        Locale locale = new Locale("", countryCodes[i]);
        String code = locale.getCountry();
        String name = locale.getDisplayCountry();
 
        listCountry[i] = new Country(code, name);
    }
 
    Arrays.sort(listCountry);
 
    return listCountry;
}
*/
//Country[] listCountry = createCountryList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        paneHeader = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        paneBody = new javax.swing.JPanel();
        FieldNIF = new javax.swing.JTextField();
        GO = new javax.swing.JButton();
        insert_comment = new javax.swing.JLabel();
        surname2 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        doctype = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        DocumentLabel = new javax.swing.JLabel();
        phonenumber1 = new javax.swing.JTextField();
        phonenumber2 = new javax.swing.JTextField();
        fax = new javax.swing.JTextField();
        cpost = new javax.swing.JTextField();
        door = new javax.swing.JTextField();
        floor = new javax.swing.JTextField();
        bloc = new javax.swing.JTextField();
        flat = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        streetnum = new javax.swing.JTextField();
        via = new javax.swing.JTextField();
        userid = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        pobl = new javax.swing.JTextField();
        javax.swing.JComboBox<Country> comboCountry = new javax.swing.JComboBox<>();
        photoID = new javax.swing.JLabel();
        paneFooter = new javax.swing.JPanel();
        footnote = new javax.swing.JLabel();
        aboutus = new javax.swing.JButton();

        regform = new javax.swing.JButton();
        contactme = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        editbt = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Segistel Client Base");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        setIconImage(getIconImage());
        setName("frame"); // NOI18N
        setResizable(false);

        paneHeader.setBackground(new java.awt.Color(51, 51, 51));

        header.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText(" Segistel");

        logo.setIcon(new javax.swing.ImageIcon("/Users/AliS2019/NetBeansProjects/SegistelUI/src/com/FinalUI/icons/logo128x128.png")); // NOI18N

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneBody.setBackground(new java.awt.Color(102, 102, 102));

        FieldNIF.setBackground(new java.awt.Color(51, 51, 51));
        FieldNIF.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldNIF.setForeground(new java.awt.Color(255, 255, 255));
        FieldNIF.setText("CIF | NIF | NIE | PASAPORTE");
        FieldNIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldNIFMouseClicked(evt);
            }
        });
        FieldNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNIFActionPerformed(evt);
            }
        });
        FieldNIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNIFKeyPressed(evt);
            }
        });

        GO.setBackground(new java.awt.Color(51, 51, 51));
        GO.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        GO.setForeground(new java.awt.Color(255, 255, 255));
        GO.setIcon(new javax.swing.ImageIcon("/Users/AliS2019/NetBeansProjects/SegistelUI/src/com/FinalUI/icons/search32x32.png")); // NOI18N
        GO.setText("Search");
        GO.setDoubleBuffered(true);
        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });

        insert_comment.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        insert_comment.setForeground(new java.awt.Color(255, 255, 255));
        insert_comment.setText("Inserta numero de su documento");

        surname2.setEditable(false);
        surname2.setBackground(new java.awt.Color(51, 51, 51));
        surname2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        surname2.setForeground(new java.awt.Color(155, 155, 155));
        surname2.setText("Apellido 2");
        surname2.setToolTipText("");
        surname2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surname2MouseClicked(evt);
            }
        });

        name.setEditable(false);
        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        name.setForeground(new java.awt.Color(155, 155, 155));
        name.setText("Nombre");
        name.setActionCommand("<Not Set>");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        surname.setEditable(false);
        surname.setBackground(new java.awt.Color(51, 51, 51));
        surname.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        surname.setForeground(new java.awt.Color(155, 155, 155));
        surname.setText("Apellido 1");
        surname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surnameMouseClicked(evt);
            }
        });

        doctype.setEditable(false);
        doctype.setBackground(new java.awt.Color(51, 51, 51));
        doctype.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        doctype.setForeground(new java.awt.Color(155, 155, 155));
        doctype.setText("NIE");
        doctype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctypeMouseClicked(evt);
            }
        });
        doctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctypeActionPerformed(evt);
            }
        });

        email.setEditable(false);
        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        email.setForeground(new java.awt.Color(155, 155, 155));
        email.setText("E-Mail address");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        day.setEditable(false);
        day.setText("DD");
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        dob.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.setText("Fecha de Nacimiento:");
        dob.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        year.setEditable(false);
        year.setText("YYYY");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        month.setEditable(false);
        month.setText("MONTH");
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        DocumentLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        DocumentLabel.setForeground(new java.awt.Color(255, 255, 255));
        DocumentLabel.setText("Numero de Documento:");
        DocumentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        phonenumber1.setEditable(false);
        phonenumber1.setBackground(new java.awt.Color(51, 51, 51));
        phonenumber1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        phonenumber1.setForeground(new java.awt.Color(155, 155, 155));
        phonenumber1.setText("Numero Telefono");
        phonenumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumber1ActionPerformed(evt);
            }
        });

        phonenumber2.setEditable(false);
        phonenumber2.setBackground(new java.awt.Color(51, 51, 51));
        phonenumber2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        phonenumber2.setForeground(new java.awt.Color(155, 155, 155));
        phonenumber2.setText("Numero Telefono Adicional");
        phonenumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumber2ActionPerformed(evt);
            }
        });

        fax.setEditable(false);
        fax.setBackground(new java.awt.Color(51, 51, 51));
        fax.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        fax.setForeground(new java.awt.Color(155, 155, 155));
        fax.setText("FAX");
        fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxActionPerformed(evt);
            }
        });

        cpost.setEditable(false);
        cpost.setBackground(new java.awt.Color(51, 51, 51));
        cpost.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        cpost.setForeground(new java.awt.Color(155, 155, 155));
        cpost.setText("CODIGO POSTAL");
        cpost.setToolTipText("");
        cpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpostActionPerformed(evt);
            }
        });

        door.setEditable(false);
        door.setBackground(new java.awt.Color(51, 51, 51));
        door.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        door.setForeground(new java.awt.Color(155, 155, 155));
        door.setText("PUERTA");
        door.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorActionPerformed(evt);
            }
        });

        floor.setEditable(false);
        floor.setBackground(new java.awt.Color(51, 51, 51));
        floor.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        floor.setForeground(new java.awt.Color(155, 155, 155));
        floor.setText("ESC.");
        floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorActionPerformed(evt);
            }
        });

        bloc.setEditable(false);
        bloc.setBackground(new java.awt.Color(51, 51, 51));
        bloc.setForeground(new java.awt.Color(155, 155, 155));
        bloc.setText("BLOQUE");
        bloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blocActionPerformed(evt);
            }
        });

        flat.setBackground(new java.awt.Color(51, 51, 51));
        flat.setForeground(new java.awt.Color(155, 155, 155));
        flat.setText("PISO");
        flat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatActionPerformed(evt);
            }
        });

        street.setEditable(false);
        street.setBackground(new java.awt.Color(51, 51, 51));
        street.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        street.setForeground(new java.awt.Color(155, 155, 155));
        street.setText("Dirección");

        streetnum.setEditable(false);
        streetnum.setBackground(new java.awt.Color(51, 51, 51));
        streetnum.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        streetnum.setForeground(new java.awt.Color(155, 155, 155));
        streetnum.setText("NUMERO");
        streetnum.setToolTipText("");

        via.setEditable(false);
        via.setBackground(new java.awt.Color(51, 51, 51));
        via.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        via.setForeground(new java.awt.Color(155, 155, 155));
        via.setText("TIPO VIA");
        via.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viaActionPerformed(evt);
            }
        });

        userid.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userid.setText("Client ID:");

        sex.setBackground(new java.awt.Color(0, 0, 0));
        sex.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        sex.setForeground(new java.awt.Color(255, 255, 255));
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });

        pobl.setEditable(false);
        pobl.setBackground(new java.awt.Color(51, 51, 51));
        pobl.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        pobl.setForeground(new java.awt.Color(155, 155, 155));
        pobl.setText("POBLACIÓN");
        pobl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poblActionPerformed(evt);
            }
        });

        comboCountry.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N

        photoID.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        photoID.setForeground(new java.awt.Color(255, 255, 255));
        photoID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        photoID.setText("Photo ID:");

        javax.swing.GroupLayout paneBodyLayout = new javax.swing.GroupLayout(paneBody);
        paneBody.setLayout(paneBodyLayout);
        paneBodyLayout.setHorizontalGroup(
            paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(paneBodyLayout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insert_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addComponent(FieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneBodyLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DocumentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doctype, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(218, 218, 218)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBodyLayout.createSequentialGroup()
                                .addComponent(streetnum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flat, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(door, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(via)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bloc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpost, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pobl))
                        .addGap(173, 173, 173))
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addComponent(photoID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paneBodyLayout.setVerticalGroup(
            paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insert_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DocumentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctype, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCountry)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(via, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(streetnum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(door, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpost, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pobl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userid)
                        .addGap(18, 18, 18)
                        .addComponent(photoID)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phonenumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phonenumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        paneFooter.setBackground(new java.awt.Color(51, 51, 51));

        footnote.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        footnote.setForeground(new java.awt.Color(255, 255, 255));
        footnote.setText("Copyright © 2021 CompanyName LTD. All rights reserved!");

        aboutus.setBackground(new java.awt.Color(0, 153, 153));
        aboutus.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setIcon(new javax.swing.ImageIcon("/Users/AliS2019/NetBeansProjects/SegistelUI/src/com/FinalUI/icons/au32x32.png")); // NOI18N
        aboutus.setText("About Us");
        aboutus.setActionCommand("");
        aboutus.setMaximumSize(new java.awt.Dimension(207, 202));
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });

        regform.setBackground(new java.awt.Color(255, 51, 51));
        regform.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        regform.setForeground(new java.awt.Color(255, 255, 255));
        regform.setIcon(new javax.swing.ImageIcon("/Users/AliS2019/NetBeansProjects/SegistelUI/src/com/FinalUI/icons/sing32x32.png")); // NOI18N
        regform.setText("Sign Up");

        contactme.setBackground(new java.awt.Color(255, 153, 0));
        contactme.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        contactme.setForeground(new java.awt.Color(255, 255, 255));
        contactme.setIcon(new javax.swing.ImageIcon("/Users/AliS2019/NetBeansProjects/SegistelUI/src/com/FinalUI/icons/32x32.png")); // NOI18N
        contactme.setText("Contact Administrator");

        submit.setBackground(new java.awt.Color(51, 51, 51));
        submit.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.setEnabled(false);
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        editbt.setBackground(new java.awt.Color(51, 51, 51));
        editbt.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        editbt.setForeground(new java.awt.Color(255, 255, 255));
        editbt.setText("Edit");
        editbt.setEnabled(false);
        editbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneFooterLayout = new javax.swing.GroupLayout(paneFooter);
        paneFooter.setLayout(paneFooterLayout);
        paneFooterLayout.setHorizontalGroup(
            paneFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFooterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(footnote, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regform, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editbt)
                .addGap(39, 39, 39))
        );
        paneFooterLayout.setVerticalGroup(
            paneFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footnote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit)
                    .addComponent(editbt)
                    .addComponent(regform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        aboutus.getAccessibleContext().setAccessibleName("");
        regform.getAccessibleContext().setAccessibleName("regfunc");
        contactme.getAccessibleContext().setAccessibleName("contactform");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneFooter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneBody, javax.swing.GroupLayout.PREFERRED_SIZE, 702, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNIFActionPerformed
     /*  
       String fieldeclaration = FieldNIF.getText().toUpperCase();
       boolean algorithmCIF;
       boolean algorithmNIE;
       boolean algorithmNIF;
       
       algorithmCIF = fieldeclaration.charAt(1) == '-' && Character.isLetter(fieldeclaration.charAt(0));
       algorithmNIE = Character.isLetter(fieldeclaration.charAt(0))
                    && Character.isLetter(fieldeclaration.charAt(fieldeclaration.length() - 1));
       algorithmNIF = Character.isLetter(fieldeclaration.charAt(fieldeclaration.length()));

       if (fieldeclaration.equals(algorithmCIF) || fieldeclaration.equals(algorithmNIE) || fieldeclaration.equals(algorithmNIF)){
       
       }
        */
    }//GEN-LAST:event_FieldNIFActionPerformed

    private void FieldNIFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldNIFMouseClicked
        //Clearing TextField to allow user to write without cleanig
        if(FieldNIF.isEditable()){
            FieldNIF.setText("");
        } 
    }//GEN-LAST:event_FieldNIFMouseClicked

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        if(name.isEditable()){
            name.setText("");
            name.setForeground(new java.awt.Color(255, 255, 255));
        }
        
    }//GEN-LAST:event_nameMouseClicked

    private void surnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surnameMouseClicked
       if(name.isEditable()){
            surname.setText("");
            surname.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_surnameMouseClicked

    private void surname2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surname2MouseClicked
       if(name.isEditable()){
            surname2.setText("");
            surname2.setForeground(new java.awt.Color(255, 255, 255));
       }
    }//GEN-LAST:event_surname2MouseClicked

    private void doctypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctypeMouseClicked
        if(name.isEditable()){
            doctype.setText("");
            doctype.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_doctypeMouseClicked

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
      
        
              /*for(int i = 0; i < sexo.length; i++ ){
                  sex.addElement(options[i][0]);
                  if(getValue(i).equals(sexo)){
                      selectedIndex = i;
                  }
              }           
             }
        */
    }//GEN-LAST:event_sexActionPerformed

    private void editbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbtMouseClicked
             if(editbt.isEnabled()== true){
                via.setEditable(true);
                streetnum.setEditable(true);
                street.setEditable(true);
                flat.setEditable(true);
                bloc.setEditable(true);
                floor.setEditable(true);
                door.setEditable(true);
                cpost.setEditable(true);
                fax.setEditable(true);
                phonenumber2.setEditable(true);
                phonenumber1.setEditable(true);
                month.setEditable(true);
                day.setEditable(false);
                year.setEditable(false);
                sex.setEditable(false);
                email.setEditable(true);
  //              nationality.setEditable(true);
                doctype.setEditable(false);
                surname.setEditable(true);
                name.setEditable(true);
                surname2.setEditable(true);
             }
    }//GEN-LAST:event_editbtMouseClicked

    private void poblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poblActionPerformed

    private void FieldNIFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNIFKeyPressed
            
    }//GEN-LAST:event_FieldNIFKeyPressed

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
          
    }//GEN-LAST:event_aboutusMouseClicked
    
    private void submitMouseClicked(java.awt.event.MouseEvent evt){
        
    }
    
    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutusActionPerformed
      
    }// GEN-LAST:event_aboutusActionPerformed

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nationalityActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameActionPerformed

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_dayActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_yearActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_monthActionPerformed

    private void doctypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doctypeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_doctypeActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailActionPerformed

    private void phonenumber1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phonenumber1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_phonenumber1ActionPerformed

    private void phonenumber2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phonenumber2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_phonenumber2ActionPerformed

    private void faxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_faxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_faxActionPerformed

    private void cpostActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cpostActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cpostActionPerformed

    private void doorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_doorActionPerformed

    private void floorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_floorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_floorActionPerformed

    private void blocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_blocActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_blocActionPerformed

    private void flatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_flatActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_flatActionPerformed

    private void viaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_viaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_viaActionPerformed

    private void GOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GOActionPerformed
        try {
           
            Connection con = null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:XE", "EU", "12345");
            Statement stmt = con.createStatement();
           
            
            String SQL = ("SELECT * FROM CLIENTES WHERE nif='" + FieldNIF.getText().toUpperCase() + "'");

            ResultSet rs = stmt.executeQuery(SQL);
            
            if (rs.next()) {
                String nombre = rs.getString("nombre");
                String nombre2 = rs.getString("nombre2");
                String apellidos = rs.getString("apellidos");
                String apellidos2 = rs.getString("apellido1");
                String vias = rs.getString("via");

                String direccion = rs.getString("direccion");
                String bloque = rs.getString("bloque");
                String escalera = rs.getString("escalera");
                String numero = rs.getString("numero");
                String piso = rs.getString("piso");
                String puerta = rs.getString("puerta");
                String domicilio = rs.getString("domicilio");
                String poblacion = rs.getString("poblacion");
                String cpostal = rs.getString("cpostal");
                String provincia = rs.getString("provincia");
                String nif = rs.getString("nif");
                String nacionalid = rs.getString("nacionalid");
              //  String sexo = rs.getString("sexo");
             //   String fecha_nac = rs.getString("fecha_nac");
                String telf = rs.getString("telf");
                String telf2 = rs.getString("telf2");
                String faxis = rs.getString("fax");
                String codiclient = rs.getString("codiclient");
                String dia = rs.getString("fecha_nac");
                String mes = rs.getString("fecha_nac");
                String ano = rs.getString("fecha_nac");
                
                
                header.setText(nombre + " " + nombre2 + " " + apellidos + " " + apellidos2 + " ");
                name.setText(nombre + " " + nombre2 + " ");
                name.setForeground(new java.awt.Color(255, 255, 255));
                
                surname.setText(apellidos + " ");
                surname.setForeground(new java.awt.Color(255,255,255));
                
                surname2.setText(apellidos2 + " ");
                surname2.setForeground(new java.awt.Color(255,255,255));
                
                via.setText(vias + "");
                via.setForeground(new java.awt.Color(255,255,255));
                
                street.setText(direccion + "");
                street.setForeground(new java.awt.Color(255,255,255));
                
                streetnum.setText(numero + "");
                streetnum.setForeground(new java.awt.Color(255,255,255));
                
                bloc.setText(bloque + "");
                bloc.setForeground(new java.awt.Color(255,255,255));
                
                floor.setText(escalera + "");
                floor.setForeground(new java.awt.Color(255,255,255));
                
                door.setText(puerta + "");
                door.setForeground(new java.awt.Color(255,255,255));
                
                cpost.setForeground(new java.awt.Color(255,255,255));
                cpost.setText(cpostal + "");
                
 //               nationality.setForeground(new java.awt.Color(255,255,255));
 //               nationality.setText(nacionalid + "");
                
                doctype.setForeground(new java.awt.Color(255,255,255));
                doctype.setText(nif + "");
            
                phonenumber1.setForeground(new java.awt.Color(255,255,255));
                phonenumber1.setText(telf + "");

                phonenumber2.setForeground(new java.awt.Color(255,255,255));
                phonenumber2.setText(telf2 + "");

                fax.setForeground(new java.awt.Color(255,255,255));
                fax.setText(faxis + "");

                flat.setForeground(new java.awt.Color(255,255,255));
                flat.setText(piso + "");


                //DATE OF BIRTH
                day.setForeground(new java.awt.Color(255,255,255));
                day.setText(dia.substring(0,2) + "");
                month.setForeground(new java.awt.Color(255,255,255));
                month.setText(mes.substring(2,4) + "");
                year.setForeground(new java.awt.Color(255,255,255));
                year.setText(ano.substring(4,6) + "");

                userid.setText("Client ID: " + codiclient + "");
                userid.setForeground(new java.awt.Color(255,41,156));
                
                editbt.setEnabled(true);
            
            } else {
                
                    surname2.setText("Apellido 2");
                    name.setText("Nombre");
                    surname.setText("Apellido 1");
                    doctype.setText("NIE");
   //                 nationality.setText("Nacionalidad");
                    email.setText("E-Mail address");
                    day.setText("DD");
                    //sex.setText("Sexo");
                    year.setText("YYYY");
                    month.setText("MONTH");
                    phonenumber1.setText("Numero Telefono");
                    phonenumber2.setText("Numero Telefono Adicional");
                    fax.setText("FAX");
                    cpost.setText("Codigo Postal");
                    door.setText("PUERTA");
                    floor.setText("ESC.");
                    bloc.setText("BLOQUE");
                    flat.setText("PISO");
                    street.setText("Domicilio");
                    streetnum.setText("Numero");
                    via.setText("TIPO VIA");
                
                header.setText("No User Found!");
                
                via.setEditable(true);
                streetnum.setEditable(true);
                street.setEditable(true);
                flat.setEditable(true);
                bloc.setEditable(true);
                floor.setEditable(true);
                door.setEditable(true);
                cpost.setEditable(true);
                fax.setEditable(true);
                phonenumber2.setEditable(true);
                phonenumber1.setEditable(true);
                month.setEditable(true);
                day.setEditable(true);
                year.setEditable(true);
                sex.setEditable(true);
                email.setEditable(true);
 //               nationality.setEditable(true);
                doctype.setEditable(true);
                surname.setEditable(true);
                name.setEditable(true);
                surname2.setEditable(true);
                userid.setText("Client ID: 000NU");
                
                
                submit.setEnabled(true);
                editbt.setEnabled(false);
                
            }
        } catch (Exception e) {
            header.setText(("OUT: " + e.getMessage()));
        }

    }// GEN-LAST:event_GOActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignUI().setVisible(true);
              //  new AboutUI().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DocumentLabel;
    private javax.swing.JTextField FieldNIF;
    private javax.swing.JButton GO;
    private javax.swing.JButton aboutus;
    private javax.swing.JTextField bloc;
    private javax.swing.JButton contactme;
    private javax.swing.JTextField cpost;
    private javax.swing.JTextField day;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField doctype;
    private javax.swing.JTextField door;
    private javax.swing.JButton editbt;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fax;
    private javax.swing.JTextField flat;
    private javax.swing.JTextField floor;
    private javax.swing.JLabel footnote;
    private javax.swing.JLabel header;
    private javax.swing.JLabel insert_comment;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField month;
    private javax.swing.JTextField name;
    private javax.swing.JPanel paneBody;
    private javax.swing.JPanel paneFooter;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JTextField phonenumber1;
    private javax.swing.JTextField phonenumber2;
    private javax.swing.JLabel photoID;
    private javax.swing.JTextField pobl;
    private javax.swing.JButton regform;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JTextField street;
    private javax.swing.JTextField streetnum;
    private javax.swing.JButton submit;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField surname2;
    private javax.swing.JLabel userid;
    private javax.swing.JTextField via;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

}
