/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/* Software version 1.0.0.23072021  */ 
/* Software Iteration 2, version 1.0.1.10282021 */
package com.FinalUI;

import java.awt.Color;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;


/**
 *
 * @author AliS2019
 */
public class DesignUI extends javax.swing.JFrame{

    /**
     * Creates new form DesignUI
     */
    public DesignUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        about_frame = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        frame_u = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        paneHeader = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        paneBody = new javax.swing.JPanel();
        surname2 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        doctype = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        dob_title = new javax.swing.JLabel();
        DocumentLabel = new javax.swing.JLabel();
        phonenumber1 = new javax.swing.JTextField();
        phonenumber2 = new javax.swing.JTextField();
        fax = new javax.swing.JTextField();
        cpost = new javax.swing.JTextField();
        door = new javax.swing.JTextField();
        floor = new javax.swing.JTextField();
        bloc = new javax.swing.JTextField();
        flat = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        streetnum = new javax.swing.JTextField();
        userid = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        pobl = new javax.swing.JTextField();
        photoID = new javax.swing.JLabel();
        comboCountry = new javax.swing.JComboBox<>(getAllCountries());
        name_title = new javax.swing.JLabel();
        surname_title2 = new javax.swing.JLabel();
        surnname_title = new javax.swing.JLabel();
        email_title = new javax.swing.JLabel();
        sex_title = new javax.swing.JLabel();
        nationality_title = new javax.swing.JLabel();
        fax_title = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        phone_title1 = new javax.swing.JLabel();
        phone_title2 = new javax.swing.JLabel();
        address_title = new javax.swing.JLabel();
        vile_title = new javax.swing.JLabel();
        comboVia = new javax.swing.JComboBox<>();
        flat_title = new javax.swing.JLabel();
        number_title = new javax.swing.JLabel();
        door_title = new javax.swing.JLabel();
        city_title = new javax.swing.JLabel();
        postal_title = new javax.swing.JLabel();
        bloc_title = new javax.swing.JLabel();
        floor_title1 = new javax.swing.JLabel();
        nac_msg = new javax.swing.JTextField();
        sexo_field = new javax.swing.JTextField();
        postalcode = new javax.swing.JComboBox<>();
        formatedfield = new javax.swing.JFormattedTextField();
        search_engine = new javax.swing.JLayeredPane();
        GO = new javax.swing.JButton();
        FieldNIF = new javax.swing.JTextField();
        insert_comment = new javax.swing.JLabel();
        paneFooter = new javax.swing.JPanel();
        footnote = new javax.swing.JLabel();
        aboutus = new javax.swing.JButton();

        regform = new javax.swing.JButton();
        contactme = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        editbt = new javax.swing.JButton();

        about_frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        about_frame.setTitle("About Us");

        javax.swing.GroupLayout about_frameLayout = new javax.swing.GroupLayout(about_frame.getContentPane());
        about_frame.getContentPane().setLayout(about_frameLayout);
        about_frameLayout.setHorizontalGroup(
            about_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        about_frameLayout.setVerticalGroup(
            about_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        frame_u.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frame_u.setTitle("About Us");
        frame_u.setBackground(new java.awt.Color(0, 0, 204));
        frame_u.setBounds(new java.awt.Rectangle(0, 0, 350, 400));
        frame_u.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout frame_uLayout = new javax.swing.GroupLayout(frame_u.getContentPane());
        frame_u.getContentPane().setLayout(frame_uLayout);
        frame_uLayout.setHorizontalGroup(
            frame_uLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frame_uLayout.setVerticalGroup(
            frame_uLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        frame_u.getAccessibleContext().setAccessibleParent(this);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleParent(frame_u);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Segistel Client Base");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        setIconImage(getIconImage());
        setName("frame"); // NOI18N
        setResizable(false);

        paneHeader.setBackground(new java.awt.Color(51, 51, 51));

        header.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setText("Segistel");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo128x128.png"))); // NOI18N

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneBody.setBackground(new java.awt.Color(102, 102, 102));

        surname2.setEditable(false);
        surname2.setBackground(new java.awt.Color(51, 51, 51));
        surname2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        surname2.setForeground(new java.awt.Color(155, 155, 155));
        surname2.setText("Apellido 2");
        surname2.setToolTipText("");
        surname2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surname2MouseClicked(evt);
            }
        });

        name.setEditable(false);
        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        name.setForeground(new java.awt.Color(155, 155, 155));
        name.setText("Nombre");
        name.setActionCommand("<Not Set>");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });

        surname.setEditable(false);
        surname.setBackground(new java.awt.Color(51, 51, 51));
        surname.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        surname.setForeground(new java.awt.Color(155, 155, 155));
        surname.setText("Apellido 1");
        surname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surnameMouseClicked(evt);
            }
        });
        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });

        doctype.setEditable(false);
        doctype.setBackground(new java.awt.Color(51, 51, 51));
        doctype.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        doctype.setForeground(new java.awt.Color(155, 155, 155));
        doctype.setText("NIE");
        doctype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctypeMouseClicked(evt);
            }
        });

        email.setEditable(false);
        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        email.setForeground(new java.awt.Color(155, 155, 155));
        email.setText("E-Mail address");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });

        dob_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        dob_title.setForeground(new java.awt.Color(255, 255, 255));
        dob_title.setText("Fecha de Nacimiento:");
        dob_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DocumentLabel.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        DocumentLabel.setForeground(new java.awt.Color(255, 255, 255));
        DocumentLabel.setText("Numero de Documento:");
        DocumentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        phonenumber1.setEditable(false);
        phonenumber1.setBackground(new java.awt.Color(51, 51, 51));
        phonenumber1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        phonenumber1.setForeground(new java.awt.Color(155, 155, 155));
        phonenumber1.setText("Numero Telefono");
        phonenumber1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phonenumber1MouseClicked(evt);
            }
        });

        phonenumber2.setEditable(false);
        phonenumber2.setBackground(new java.awt.Color(51, 51, 51));
        phonenumber2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        phonenumber2.setForeground(new java.awt.Color(155, 155, 155));
        phonenumber2.setText("Numero Telefono Adicional");
        phonenumber2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phonenumber2MouseClicked(evt);
            }
        });

        fax.setEditable(false);
        fax.setBackground(new java.awt.Color(51, 51, 51));
        fax.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        fax.setForeground(new java.awt.Color(155, 155, 155));
        fax.setText("FAX");
        fax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faxMouseClicked(evt);
            }
        });

        cpost.setEditable(false);
        cpost.setBackground(new java.awt.Color(51, 51, 51));
        cpost.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        cpost.setForeground(new java.awt.Color(155, 155, 155));
        cpost.setText("CODIGO POSTAL");
        cpost.setToolTipText("");
        cpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpostActionPerformed(evt);
            }
        });

        door.setEditable(false);
        door.setBackground(new java.awt.Color(51, 51, 51));
        door.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        door.setForeground(new java.awt.Color(155, 155, 155));
        door.setText("PUERTA");
        door.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doorMouseClicked(evt);
            }
        });
        door.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorActionPerformed(evt);
            }
        });

        floor.setEditable(false);
        floor.setBackground(new java.awt.Color(51, 51, 51));
        floor.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        floor.setForeground(new java.awt.Color(155, 155, 155));
        floor.setText("ESC.");
        floor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorMouseClicked(evt);
            }
        });
        floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorActionPerformed(evt);
            }
        });

        bloc.setEditable(false);
        bloc.setBackground(new java.awt.Color(51, 51, 51));
        bloc.setForeground(new java.awt.Color(155, 155, 155));
        bloc.setText("BLOQUE");
        bloc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blocMouseClicked(evt);
            }
        });
        bloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blocActionPerformed(evt);
            }
        });

        flat.setEditable(false);
        flat.setBackground(new java.awt.Color(51, 51, 51));
        flat.setForeground(new java.awt.Color(155, 155, 155));
        flat.setText("PISO");
        flat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flatMouseClicked(evt);
            }
        });
        flat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatActionPerformed(evt);
            }
        });

        street.setEditable(false);
        street.setBackground(new java.awt.Color(51, 51, 51));
        street.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        street.setForeground(new java.awt.Color(155, 155, 155));
        street.setText("Dirección");
        street.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                streetMouseClicked(evt);
            }
        });

        streetnum.setEditable(false);
        streetnum.setBackground(new java.awt.Color(51, 51, 51));
        streetnum.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        streetnum.setForeground(new java.awt.Color(155, 155, 155));
        streetnum.setText("NUMERO");
        streetnum.setToolTipText("");
        streetnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                streetnumMouseClicked(evt);
            }
        });

        userid.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        userid.setForeground(new java.awt.Color(255, 255, 255));
        userid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userid.setText("Client ID:");

        sex.setBackground(new java.awt.Color(255, 255, 255));
        sex.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        sex.setForeground(new java.awt.Color(255, 255, 255));
        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        sex.setEnabled(false);
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });

        pobl.setEditable(false);
        pobl.setBackground(new java.awt.Color(51, 51, 51));
        pobl.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        pobl.setForeground(new java.awt.Color(155, 155, 155));
        pobl.setText("POBLACIÓN");
        pobl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poblActionPerformed(evt);
            }
        });

        photoID.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        photoID.setForeground(new java.awt.Color(255, 255, 255));
        photoID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        photoID.setText("Photo ID:");

        comboCountry.setBackground(new java.awt.Color(255, 255, 255));
        comboCountry.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        comboCountry.setEnabled(false);
        comboCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCountryActionPerformed(evt);
            }
        });

        name_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        name_title.setForeground(new java.awt.Color(255, 255, 255));
        name_title.setText("Nombre:");
        name_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        surname_title2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        surname_title2.setForeground(new java.awt.Color(255, 255, 255));
        surname_title2.setText("Apellido 2:");
        surname_title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        surnname_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        surnname_title.setForeground(new java.awt.Color(255, 255, 255));
        surnname_title.setText("Apellido 1:");
        surnname_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        email_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        email_title.setForeground(new java.awt.Color(255, 255, 255));
        email_title.setText("Correo Electrónico (Email)*:");
        email_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        sex_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        sex_title.setForeground(new java.awt.Color(255, 255, 255));
        sex_title.setText("Sexo");
        sex_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nationality_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        nationality_title.setForeground(new java.awt.Color(255, 255, 255));
        nationality_title.setText("Nacionalidad:");
        nationality_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        fax_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        fax_title.setForeground(new java.awt.Color(255, 255, 255));
        fax_title.setText("Fax: ");
        fax_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setEnabled(false);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", " ", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", " ", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", " ", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", " ", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", " ", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", " ", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", " ", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", " ", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", " ", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", " ", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", " ", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901" }));
        year.setEnabled(false);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        month.setEnabled(false);

        phone_title1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        phone_title1.setForeground(new java.awt.Color(255, 255, 255));
        phone_title1.setText("Numero de Teléfono: ");
        phone_title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        phone_title2.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        phone_title2.setForeground(new java.awt.Color(255, 255, 255));
        phone_title2.setText("Numero de Teléfono Adicional: ");
        phone_title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        address_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        address_title.setForeground(new java.awt.Color(255, 255, 255));
        address_title.setText("Dirección:");
        address_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vile_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        vile_title.setForeground(new java.awt.Color(255, 255, 255));
        vile_title.setText("Via:");
        vile_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboVia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARRER", "PASSEIG", "AVINGUDA", " " }));
        comboVia.setSelectedIndex(1);
        comboVia.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        comboVia.setEnabled(false);

        flat_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        flat_title.setForeground(new java.awt.Color(255, 255, 255));
        flat_title.setText("Piso:");
        flat_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        number_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        number_title.setForeground(new java.awt.Color(255, 255, 255));
        number_title.setText("Numero:");
        number_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        door_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        door_title.setForeground(new java.awt.Color(255, 255, 255));
        door_title.setText("Puerta:");
        door_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        city_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        city_title.setForeground(new java.awt.Color(255, 255, 255));
        city_title.setText("Población:");
        city_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        postal_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        postal_title.setForeground(new java.awt.Color(255, 255, 255));
        postal_title.setText("Codigo Postal:");
        postal_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bloc_title.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        bloc_title.setForeground(new java.awt.Color(255, 255, 255));
        bloc_title.setText("Bloque:");
        bloc_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        floor_title1.setFont(new java.awt.Font("Montserrat", 1, 13)); // NOI18N
        floor_title1.setForeground(new java.awt.Color(255, 255, 255));
        floor_title1.setText("Escalera:");
        floor_title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nac_msg.setEditable(false);
        nac_msg.setBackground(new java.awt.Color(51, 51, 51));
        nac_msg.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        nac_msg.setForeground(new java.awt.Color(153, 153, 153));
        nac_msg.setText("Nacionalidad");

        sexo_field.setEditable(false);
        sexo_field.setBackground(new java.awt.Color(51, 51, 51));
        sexo_field.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        sexo_field.setForeground(new java.awt.Color(153, 153, 153));
        sexo_field.setText("Sexo");

        postalcode.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        postalcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08001", "08002", "08003", "08004", "08005", "08006", "08007", "08008", "08009", "08010", " " }));
        postalcode.setActionCommand("");
        postalcode.setEnabled(false);

        formatedfield.setBackground(new java.awt.Color(51, 51, 51));
        formatedfield.setForeground(new java.awt.Color(255, 255, 255));
        formatedfield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        formatedfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        formatedfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatedfieldActionPerformed(evt);
            }
        });

        search_engine.setBorder(new javax.swing.border.MatteBorder(null));
        search_engine.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        GO.setBackground(new java.awt.Color(51, 51, 51));
        GO.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        GO.setForeground(new java.awt.Color(255, 255, 255));
        GO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FinalUI/icons/search32x32.png"))); // NOI18N
        GO.setText("Search");
        GO.setDoubleBuffered(true);
        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });

        FieldNIF.setBackground(new java.awt.Color(51, 51, 51));
        FieldNIF.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        FieldNIF.setForeground(new java.awt.Color(255, 255, 255));
        FieldNIF.setText("CIF | NIF | NIE | PASAPORTE");
        FieldNIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FieldNIFMouseClicked(evt);
            }
        });
        FieldNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNIFActionPerformed(evt);
            }
        });
        FieldNIF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNIFKeyPressed(evt);
            }
        });

        insert_comment.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        insert_comment.setForeground(new java.awt.Color(255, 255, 255));
        insert_comment.setText("Inserta numero de su documento");

        search_engine.setLayer(GO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search_engine.setLayer(FieldNIF, javax.swing.JLayeredPane.DEFAULT_LAYER);
        search_engine.setLayer(insert_comment, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout search_engineLayout = new javax.swing.GroupLayout(search_engine);
        search_engine.setLayout(search_engineLayout);
        search_engineLayout.setHorizontalGroup(
            search_engineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_engineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_engineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_engineLayout.createSequentialGroup()
                        .addComponent(FieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(insert_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        search_engineLayout.setVerticalGroup(
            search_engineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_engineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insert_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(search_engineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout paneBodyLayout = new javax.swing.GroupLayout(paneBody);
        paneBody.setLayout(paneBodyLayout);
        paneBodyLayout.setHorizontalGroup(
            paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBodyLayout.createSequentialGroup()
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneBodyLayout.createSequentialGroup()
                                            .addComponent(surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(surname))
                                        .addGroup(paneBodyLayout.createSequentialGroup()
                                            .addComponent(surnname_title, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(surname_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(phonenumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(nac_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sexo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email_title, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name_title, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBodyLayout.createSequentialGroup()
                                        .addComponent(formatedfield, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(month, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone_title2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(doctype, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneBodyLayout.createSequentialGroup()
                                    .addComponent(nationality_title, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sex_title, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(dob_title, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phonenumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fax_title, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(DocumentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pobl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(photoID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneBodyLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(floor_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bloc_title, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paneBodyLayout.createSequentialGroup()
                                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(city_title, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bloc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(postal_title, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cpost, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postalcode, 0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBodyLayout.createSequentialGroup()
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(streetnum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(number_title, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(flat_title, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(door_title, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(flat, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(door, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBodyLayout.createSequentialGroup()
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(comboVia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(paneBodyLayout.createSequentialGroup()
                                .addComponent(vile_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41)))
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address_title, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(635, 635, 635))
            .addGroup(paneBodyLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(search_engine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneBodyLayout.setVerticalGroup(
            paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_engine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vile_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(address_title)))
                    .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name_title, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phone_title1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboVia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phonenumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(door_title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(number_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(flat_title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(surname_title2)
                        .addComponent(surnname_title)
                        .addComponent(phone_title2)))
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetnum, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(door, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonenumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dob_title, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloc_title)
                            .addComponent(postal_title)
                            .addComponent(fax_title)
                            .addComponent(floor_title1)))
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloc, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpost, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postalcode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatedfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocumentLabel)
                    .addComponent(city_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pobl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctype, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sex_title, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userid))
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addComponent(nationality_title, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nac_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(paneBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_title)
                        .addGap(12, 12, 12)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneBodyLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(photoID)))
                .addGap(28, 28, 28))
        );

        paneFooter.setBackground(new java.awt.Color(51, 51, 51));

        footnote.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        footnote.setForeground(new java.awt.Color(255, 255, 255));
        footnote.setText("Copyright © 2021 Segistel & Media Archive ltd. All rights reserved!");

        aboutus.setBackground(new java.awt.Color(0, 153, 153));
        aboutus.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        aboutus.setForeground(new java.awt.Color(255, 255, 255));
        aboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FinalUI/icons/au32x32.png"))); // NOI18N
        aboutus.setText("About Us");
        aboutus.setActionCommand("");
        aboutus.setMaximumSize(new java.awt.Dimension(207, 202));
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });

        regform.setBackground(new java.awt.Color(255, 51, 51));
        regform.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        regform.setForeground(new java.awt.Color(255, 255, 255));
        regform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FinalUI/icons/sing32x32.png"))); // NOI18N
        regform.setText("Sign Up");
        regform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regformActionPerformed(evt);
            }
        });

        contactme.setBackground(new java.awt.Color(255, 153, 0));
        contactme.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        contactme.setForeground(new java.awt.Color(255, 255, 255));
        contactme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/FinalUI/icons/32x32.png"))); // NOI18N
        contactme.setText("Contact Administrator");

        submit.setBackground(new java.awt.Color(51, 51, 51));
        submit.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.setEnabled(false);
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        editbt.setBackground(new java.awt.Color(51, 51, 51));
        editbt.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        editbt.setForeground(new java.awt.Color(255, 255, 255));
        editbt.setText("Edit");
        editbt.setEnabled(false);
        editbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneFooterLayout = new javax.swing.GroupLayout(paneFooter);
        paneFooter.setLayout(paneFooterLayout);
        paneFooterLayout.setHorizontalGroup(
            paneFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFooterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(footnote, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regform, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editbt)
                .addGap(12, 12, 12))
        );
        paneFooterLayout.setVerticalGroup(
            paneFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(footnote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit)
                    .addComponent(editbt)
                    .addComponent(regform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        aboutus.getAccessibleContext().setAccessibleName("");
        regform.getAccessibleContext().setAccessibleName("regfunc");
        contactme.getAccessibleContext().setAccessibleName("contactform");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(paneFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbtMouseClicked
             if(editbt.isEnabled()== true){
              //  via.setEditable(true);
                streetnum.setEditable(true);
                street.setEditable(true);
                flat.setEditable(true);
                bloc.setEditable(true);
                floor.setEditable(true);
                door.setEditable(true);
                cpost.setEditable(true);
                fax.setEditable(true);
                phonenumber2.setEditable(true);
                phonenumber1.setEditable(true);
     
                
                email.setEditable(true);
  //              nationality.setEditable(true);
                doctype.setEditable(false);
                surname.setEditable(true);
                name.setEditable(true);
                surname2.setEditable(true);
             }
    }//GEN-LAST:event_editbtMouseClicked
    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
        frame_u.setVisible(true);
    }//GEN-LAST:event_aboutusMouseClicked
    private void regformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regformActionPerformed
     header.setText("Registering New User");
          // FIELDS WITH DATA     
        name.setEditable(true);
        surname.setEditable(true);
        surname2.setEditable(true);
        doctype.setEditable(true);
        email.setEditable(true);
        phonenumber1.setEditable(true);
        phonenumber2.setEditable(true);
        fax.setEditable(true);
        street.setEditable(true);
        streetnum.setEditable(true);
        flat.setEditable(true);
        door.setEditable(true);
        floor.setEditable(true);
        bloc.setEditable(true);
           //COMBO BOX WITH DATA
        comboCountry.setEnabled(true);
        sex.setEnabled(true);
        comboVia.setEnabled(true);
        postalcode.setEnabled(true);
        day.setEnabled(true);
        month.setEnabled(true);
        year.setEnabled(true);
        
        
        submit.setEnabled(true);
        search_engine.setEnabled(false);
        FieldNIF.setEnabled(false);
        GO.setEnabled(false);
        insert_comment.setEnabled(false); 
                
    }//GEN-LAST:event_regformActionPerformed
    private void FieldNIFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNIFKeyPressed

    }//GEN-LAST:event_FieldNIFKeyPressed
    private void FieldNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNIFActionPerformed

        String fieldeclaration = FieldNIF.getText().toUpperCase();
        boolean algorithmCIF;
        boolean algorithmNIE;
        boolean algorithmNIF;

        algorithmCIF = fieldeclaration.charAt(1) == '-' && Character.isLetter(fieldeclaration.charAt(0));
        algorithmNIE = Character.isLetter(fieldeclaration.charAt(0))
        && Character.isLetter(fieldeclaration.charAt(fieldeclaration.length() - 1));
        algorithmNIF = Character.isLetter(fieldeclaration.charAt(fieldeclaration.length()));

        if (fieldeclaration.equals(algorithmCIF) || fieldeclaration.equals(algorithmNIE) || fieldeclaration.equals(algorithmNIF)){
            photoID.setText("TYPE OF DOC: ");

        }else {

            JOptionPane.showMessageDialog(null, "EGGS ARE NOT SUPPOSED TO BE BLACK", "Warning: " + "foo", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_FieldNIFActionPerformed
    private void FieldNIFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldNIFMouseClicked
        //Clearing TextField to allow user to write without cleanig
        if(FieldNIF.isEditable()){
            FieldNIF.setText("");
        }

    }//GEN-LAST:event_FieldNIFMouseClicked
    private void GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GOActionPerformed
    private void formatedfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatedfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatedfieldActionPerformed
    private void comboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCountryActionPerformed
        nac_msg.setText(comboCountry.getSelectedItem().toString());
        nac_msg.setForeground(Color.red);
    }//GEN-LAST:event_comboCountryActionPerformed
    private void poblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poblActionPerformed

    }//GEN-LAST:event_poblActionPerformed
    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        sexo_field.setText(sex.getSelectedItem().toString());
        sexo_field.setForeground(Color.red);

    }//GEN-LAST:event_sexActionPerformed
    private void streetnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_streetnumMouseClicked
        if(streetnum.isEditable()){
            streetnum.setText("");
            streetnum.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_streetnumMouseClicked
    private void streetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_streetMouseClicked
        if(street.isEditable()){
            street.setText("");
            street.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_streetMouseClicked
    private void flatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flatActionPerformed
    private void flatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatMouseClicked
        if(flat.isEditable()){
            flat.setText("");
            flat.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_flatMouseClicked
    private void blocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blocActionPerformed
    private void blocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blocMouseClicked
        if(bloc.isEditable()){
            bloc.setText("");
            bloc.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_blocMouseClicked
    private void floorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorActionPerformed
    private void floorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorMouseClicked
        if(floor.isEditable()){
            floor.setText("");
            floor.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_floorMouseClicked
    private void doorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doorActionPerformed
    private void doorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doorMouseClicked
        if(door.isEditable()){
            door.setText("");
            door.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_doorMouseClicked
    private void cpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpostActionPerformed
        cpost.setText(postalcode.getSelectedItem().toString());
        cpost.setForeground(Color.red);
    }//GEN-LAST:event_cpostActionPerformed
    private void faxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faxMouseClicked
        if(fax.isEditable()){
            fax.setText("");
            fax.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_faxMouseClicked
    private void phonenumber2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonenumber2MouseClicked
        if(phonenumber2.isEditable()){
            phonenumber2.setText("");
            phonenumber2.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_phonenumber2MouseClicked
    private void phonenumber1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonenumber1MouseClicked

        if(phonenumber1.isEditable()){
            phonenumber1.setText("");
            phonenumber1.setForeground(new java.awt.Color(255, 255, 255));
        }

    }//GEN-LAST:event_phonenumber1MouseClicked
    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        if(email.isEditable()){
            email.setText("");
            email.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_emailMouseClicked
    private void doctypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctypeMouseClicked
        if(name.isEditable()){
            doctype.setText("");
            doctype.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_doctypeMouseClicked
    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed
    private void surnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surnameMouseClicked
        if(name.isEditable()){
            surname.setText("");
            surname.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_surnameMouseClicked
    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        if(name.isEditable()){
            name.setText("");
            name.setForeground(new java.awt.Color(255, 255, 255));
        }

    }//GEN-LAST:event_nameMouseClicked
    private void surname2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surname2MouseClicked
        if(name.isEditable()){
            surname2.setText("");
            surname2.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_surname2MouseClicked
    private void submitMouseClicked(java.awt.event.MouseEvent evt){
        
    }
    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutusActionPerformed
      
    }// GEN-LAST:event_aboutusActionPerformed
    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nationalityActionPerformed
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameActionPerformed
    private void dayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_dayActionPerformed
    private void yearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_yearActionPerformed
    private void monthActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_monthActionPerformed
    private void doctypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doctypeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_doctypeActionPerformed
    private void emailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailActionPerformed
    private void phonenumber1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phonenumber1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_phonenumber1ActionPerformed
    private void phonenumber2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phonenumber2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_phonenumber2ActionPerformed
    private void faxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_faxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_faxActionPerformed
    private void viaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_viaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_viaActionPerformed
 
    public String[] getAllCountries(){
        String[] countries = new String[Locale.getISOCountries().length];
        String[] countryCodes = Locale.getISOCountries();
        for(int i =0; i < countryCodes.length; i++){
            Locale obj = new Locale("", countryCodes[i]);
            countries[i] = obj.getDisplayCountry();
        }
        return countries;
    }
    
    public void connection(){
         try {
           
            Connection con = null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:XE", "EU", "12345");
            Statement stmt = con.createStatement();
           
            
            String SQL = ("SELECT * FROM CLIENTES WHERE nif='" + FieldNIF.getText().toUpperCase() + "'");

            ResultSet rs = stmt.executeQuery(SQL);
            
            if (rs.next()) {
                String nombre = rs.getString("NOMBRE");
                String nombre2 = rs.getString("NOMBRE2");
                String apellidos = rs.getString("APELLIDO");
                String apellidos2 = rs.getString("APELLIDO2");
                
                String vias = rs.getString("VIA");
                String direccion = rs.getString("DIRECCION");
                String bloque = rs.getString("BLOQUE");
                String escalera = rs.getString("ESCALERA");
                String numero = rs.getString("NUMERO");
                String piso = rs.getString("PISO");
                String puerta = rs.getString("PUERTA");
                String domicilio = rs.getString("DOMICILIO");
                String poblacion = rs.getString("POBLACION");
                String cpostal = rs.getString("CPOSTAL");
                String provincia = rs.getString("PROVINCIA");
                String nif = rs.getString("NIF");
                String nacionalidad = rs.getString("NACIONALIDAD");
              //  String sexo = rs.getString("sexo");
             //   String fecha_nac = rs.getString("fecha_nac");
                String telf = rs.getString("TELF");
                String telf2 = rs.getString("TELF2");
                String faxis = rs.getString("FAX");
                String codiclient = rs.getString("id_cli");
                
                
                
                header.setText(nombre + " " + nombre2 + " " + apellidos + " " + apellidos2 + " ");
                name.setText(nombre + " " + nombre2 + " ");
                name.setForeground(new java.awt.Color(255, 255, 255));
                
                surname.setText(apellidos + " ");
                surname.setForeground(new java.awt.Color(255,255,255));
                
                surname2.setText(apellidos2 + " ");
                surname2.setForeground(new java.awt.Color(255,255,255));
                
               // via.setText(vias + "");
               //// via.setForeground(new java.awt.Color(255,255,255));
                
                street.setText(direccion + "");
                street.setForeground(new java.awt.Color(255,255,255));
                
                streetnum.setText(numero + "");
                streetnum.setForeground(new java.awt.Color(255,255,255));
                
                bloc.setText(bloque + "");
                bloc.setForeground(new java.awt.Color(255,255,255));
                
                floor.setText(escalera + "");
                floor.setForeground(new java.awt.Color(255,255,255));
                
                door.setText(puerta + "");
                door.setForeground(new java.awt.Color(255,255,255));
                
                cpost.setForeground(new java.awt.Color(255,255,255));
                cpost.setText(cpostal + "");
                
                nac_msg.setForeground(new java.awt.Color(255,255,255));
                nac_msg.setText(nacionalidad + "");
                
                doctype.setForeground(new java.awt.Color(255,255,255));
                doctype.setText(nif + "");
            
                phonenumber1.setForeground(new java.awt.Color(255,255,255));
                phonenumber1.setText(telf + "");

                phonenumber2.setForeground(new java.awt.Color(255,255,255));
                phonenumber2.setText(telf2 + "");

                fax.setForeground(new java.awt.Color(255,255,255));
                fax.setText(faxis + "");

                flat.setForeground(new java.awt.Color(255,255,255));
                flat.setText(piso + "");
                
                userid.setText("Client ID: " + codiclient + "");
                userid.setForeground(new java.awt.Color(255,41,156));
                
                editbt.setEnabled(true);
            
            } else {
                
                    surname2.setText("Apellido 2");
                    name.setText("Nombre");
                    surname.setText("Apellido 1");
                    doctype.setText("NIE");
   //                 nationality.setText("Nacionalidad");
                    email.setText("E-Mail address");
         //           day.setText("DD");
                    //sex.setText("Sexo");
         //           year.setText("YYYY");
        //            month.setText("MONTH");
                    phonenumber1.setText("Numero Telefono");
                    phonenumber2.setText("Numero Telefono Adicional");
                    fax.setText("FAX");
                    cpost.setText("Codigo Postal");
                    door.setText("PUERTA");
                    floor.setText("ESC.");
                    bloc.setText("BLOQUE");
                    flat.setText("PISO");
                    street.setText("Domicilio");
                    streetnum.setText("Numero");
           //         via.setText("TIPO VIA");
                
                header.setText("No User Found!");
                
           //     via.setEditable(true);
                streetnum.setEditable(true);
                street.setEditable(true);
                flat.setEditable(true);
                bloc.setEditable(true);
                floor.setEditable(true);
                door.setEditable(true);
                cpost.setEditable(true);
                fax.setEditable(true);
                phonenumber2.setEditable(true);
                phonenumber1.setEditable(true);
   //             month.setEditable(true);
    //            day.setEditable(true);
   //             year.setEditable(true);
                sex.setEditable(true);
                email.setEditable(true);
 //               nationality.setEditable(true);
                doctype.setEditable(true);
                surname.setEditable(true);
                name.setEditable(true);
                surname2.setEditable(true);
                userid.setText("Client ID: 000NU");
                
                
                submit.setEnabled(true);
                editbt.setEnabled(false);
                
            }
        } catch (Exception e) {
            header.setText((" " + e.getMessage()));
        }

    }
   /* public void insert()
{   
//    try {
    // connection string
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection con = DriverManager
                .getConnection("jdbc:mysql://localhost:3306/Project?user=root&password=root");
        Statement st = con.createStatement();

        st.executeUpdate("insert into Register VALUES('"
                + tf1.getText() + "','" + tf2.getText() + "','"
                + tf3.getText() + "','" + cb1.getSelectedItem()
                + "','" + tf4.getText() + "','" + tf5.getText()
                + "','" + tf6.getText() + "','" + tf7.getText()
                + "','" + tf8.getText() + "','" + tf9.getText()
                + "'," + "'" + tf10.getText() + "','"
                + tf11.getText() + "','" + tf12.getText() + "','"
                + tf13.getText() + "','" + tf14.getText() + "',"
                + "'" + tf15.getText() + "','" +tf16.getText()
                + "','" + tf17.getText() + "','" + tf18.getText()
                + "'," + "'" + tf19.getText() + "','"
                + p1.getText() + "','" + p2.getText() + "')");

        JOptionPane.showConfirmDialog(null, "Your Data Has been Inserted",
                "Result", JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE);

        st.close();
        con.close();

    }

    catch (Exception e1)

    {
        System.out.println("Exception:" + e1);
    }

}
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignUI().setVisible(true);
              //  new AboutUI().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DocumentLabel;
    private javax.swing.JTextField FieldNIF;
    private javax.swing.JButton GO;
    private javax.swing.JFrame about_frame;
    private javax.swing.JButton aboutus;
    private javax.swing.JLabel address_title;
    private javax.swing.JTextField bloc;
    private javax.swing.JLabel bloc_title;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel city_title;
    private javax.swing.JComboBox<String> comboCountry;
    private javax.swing.JComboBox<String> comboVia;
    private javax.swing.JButton contactme;
    private javax.swing.JTextField cpost;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JLabel dob_title;
    private javax.swing.JTextField doctype;
    private javax.swing.JTextField door;
    private javax.swing.JLabel door_title;
    private javax.swing.JButton editbt;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_title;
    private javax.swing.JTextField fax;
    private javax.swing.JLabel fax_title;
    private javax.swing.JTextField flat;
    private javax.swing.JLabel flat_title;
    private javax.swing.JTextField floor;
    private javax.swing.JLabel floor_title1;
    private javax.swing.JLabel footnote;
    private javax.swing.JFormattedTextField formatedfield;
    private javax.swing.JFrame frame_u;
    private javax.swing.JLabel header;
    private javax.swing.JLabel insert_comment;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField nac_msg;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_title;
    private javax.swing.JLabel nationality_title;
    private javax.swing.JLabel number_title;
    private javax.swing.JPanel paneBody;
    private javax.swing.JPanel paneFooter;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JLabel phone_title1;
    private javax.swing.JLabel phone_title2;
    private javax.swing.JTextField phonenumber1;
    private javax.swing.JTextField phonenumber2;
    private javax.swing.JLabel photoID;
    private javax.swing.JTextField pobl;
    private javax.swing.JLabel postal_title;
    private javax.swing.JComboBox<String> postalcode;
    private javax.swing.JButton regform;
    private javax.swing.JLayeredPane search_engine;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JLabel sex_title;
    private javax.swing.JTextField sexo_field;
    private javax.swing.JTextField street;
    private javax.swing.JTextField streetnum;
    private javax.swing.JButton submit;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField surname2;
    private javax.swing.JLabel surname_title2;
    private javax.swing.JLabel surnname_title;
    private javax.swing.JLabel userid;
    private javax.swing.JLabel vile_title;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables

}
